/**
 * BookNest Seed Data & Demonstration Dataset
 * Realistic college academic textbooks, categories, and initial test entities.
 */

const BookNestSeedData = {
  categories: [
    { id: 'cat-cs', name: 'Computer Science', slug: 'computer-science', description: 'Algorithms, Architecture, Theory and Programming fundamentals' },
    { id: 'cat-it', name: 'Information Technology', slug: 'information-technology', description: 'Web development, Cloud computing, Cybersecurity and Databases' },
    { id: 'cat-eng', name: 'Engineering', slug: 'engineering', description: 'Mechanical, Civil, Electrical and Electronics engineering texts' },
    { id: 'cat-commerce', name: 'Commerce & Finance', slug: 'commerce-finance', description: 'Accounting, Taxation, Financial management and Economics' },
    { id: 'cat-mgmt', name: 'Management', slug: 'management', description: 'Business strategy, Marketing, Human resources and Operations' },
    { id: 'cat-science', name: 'Science', slug: 'science', description: 'Physics, Applied Mathematics, Chemistry and Statistics' },
    { id: 'cat-exams', name: 'Competitive Exams', slug: 'competitive-exams', description: 'GATE, GRE, CAT, Placement prep and Aptitude guides' },
    { id: 'cat-ref', name: 'Reference Books', slug: 'reference-books', description: 'Dictionaries, handbooks, IEEE standards and research papers' }
  ],

  books: [
    {
      id: 'book-1',
      title: 'Data Structures and Algorithms Made Easy',
      author: 'Narasimha Karumanchi',
      isbn: '978-8193245279',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Data Structures',
      semester: 'Semester 3',
      description: 'Comprehensive guide to algorithms and data structures with step-by-step problem solving, code implementations, and complexity analysis for college exams and technical interviews.',
      price: 499,
      rentalPrice: 89,
      stock: 12,
      availableStock: 8,
      condition: 'Like New',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-10T10:00:00Z',
      featured: true
    },
    {
      id: 'book-2',
      title: 'Database Management Systems (3rd Edition)',
      author: 'Raghu Ramakrishnan & Johannes Gehrke',
      isbn: '978-0072465631',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'DBMS',
      semester: 'Semester 4',
      description: 'Standard university textbook covering relational models, SQL queries, transaction management, indexing, schema refinement, and database internals.',
      price: 650,
      rentalPrice: 110,
      stock: 10,
      availableStock: 6,
      condition: 'Good',
      rentEnabled: true,
      returnDurationDays: 45,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-12T11:30:00Z',
      featured: true
    },
    {
      id: 'book-3',
      title: 'Operating System Concepts (10th Edition)',
      author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
      isbn: '978-1119456339',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Operating Systems',
      semester: 'Semester 4',
      description: 'The famous "Dinosaur Book" covering processes, threads, CPU scheduling, synchronization primitives, deadlock avoidance, virtual memory, and storage management.',
      price: 799,
      rentalPrice: 140,
      stock: 8,
      availableStock: 3,
      condition: 'Like New',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-14T09:15:00Z',
      featured: true
    },
    {
      id: 'book-4',
      title: 'Computer Networking: A Top-Down Approach',
      author: 'James Kurose & Keith Ross',
      isbn: '978-0133594140',
      categoryId: 'cat-it',
      categoryName: 'Information Technology',
      subject: 'Computer Networks',
      semester: 'Semester 5',
      description: 'Explores the Internet architecture from application layer (HTTP, DNS) down through transport (TCP, UDP), network (IP, BGP), and link layers with practical packet analysis.',
      price: 680,
      rentalPrice: 120,
      stock: 9,
      availableStock: 5,
      condition: 'Good',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-18T14:20:00Z',
      featured: true
    },
    {
      id: 'book-5',
      title: 'Python Crash Course (3rd Edition)',
      author: 'Eric Matthes',
      isbn: '978-1718502703',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Python Programming',
      semester: 'Semester 2',
      description: 'Hands-on guide to fast-paced Python programming covering variables, lists, dictionaries, OOP classes, unit tests, and real-world project development.',
      price: 520,
      rentalPrice: 95,
      stock: 15,
      availableStock: 11,
      condition: 'New',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-20T10:00:00Z',
      featured: true
    },
    {
      id: 'book-6',
      title: 'Core Java Volume I: Fundamentals (12th Edition)',
      author: 'Cay S. Horstmann',
      isbn: '978-0137673629',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Java Programming',
      semester: 'Semester 3',
      description: 'In-depth reference and tutorial for Java SE, object-oriented concepts, generics, lambda expressions, concurrency, and robust application architecture.',
      price: 750,
      rentalPrice: 130,
      stock: 6,
      availableStock: 2,
      condition: 'Good',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-22T16:00:00Z',
      featured: false
    },
    {
      id: 'book-7',
      title: 'Full Stack Web Development with React & Node',
      author: 'Alex Banks & Eve Porcello',
      isbn: '978-1492051725',
      categoryId: 'cat-it',
      categoryName: 'Information Technology',
      subject: 'Web Development',
      semester: 'Semester 5',
      description: 'Build robust, scalable modern web applications from frontend single-page interfaces with React to RESTful backend microservices in Node.js and Express.',
      price: 590,
      rentalPrice: 105,
      stock: 14,
      availableStock: 10,
      condition: 'Like New',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-25T13:45:00Z',
      featured: true
    },
    {
      id: 'book-8',
      title: 'Artificial Intelligence: A Modern Approach (4th Ed)',
      author: 'Stuart Russell & Peter Norvig',
      isbn: '978-0134610993',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Artificial Intelligence',
      semester: 'Semester 6',
      description: 'The authoritative AI reference covering search algorithms, game playing, logic representations, probabilistic reasoning, reinforcement learning, and ethics.',
      price: 899,
      rentalPrice: 160,
      stock: 7,
      availableStock: 4,
      condition: 'New',
      rentEnabled: true,
      returnDurationDays: 45,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-01-28T09:00:00Z',
      featured: true
    },
    {
      id: 'book-9',
      title: 'Hands-On Machine Learning with Scikit-Learn & TensorFlow',
      author: 'Aurélien Géron',
      isbn: '978-1098125974',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Machine Learning',
      semester: 'Semester 6',
      description: 'Practical guide to building intelligent systems using concrete examples, minimal theory, and production-ready Python frameworks.',
      price: 840,
      rentalPrice: 150,
      stock: 11,
      availableStock: 7,
      condition: 'Like New',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-02-01T11:20:00Z',
      featured: true
    },
    {
      id: 'book-10',
      title: 'Software Engineering: A Practitioner\'s Approach',
      author: 'Roger S. Pressman & Bruce R. Maxim',
      isbn: '978-1259872976',
      categoryId: 'cat-cs',
      categoryName: 'Computer Science',
      subject: 'Software Engineering',
      semester: 'Semester 5',
      description: 'Covers agile methodologies, software requirements engineering, design principles, testing strategies, DevOps continuous integration, and project metrics.',
      price: 630,
      rentalPrice: 110,
      stock: 10,
      availableStock: 6,
      condition: 'Fair',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-02-05T14:10:00Z',
      featured: false
    },
    {
      id: 'book-11',
      title: 'Principles of Marketing (18th Edition)',
      author: 'Philip Kotler & Gary Armstrong',
      isbn: '978-0135766590',
      categoryId: 'cat-mgmt',
      categoryName: 'Management',
      subject: 'Marketing Management',
      semester: 'Semester 2',
      description: 'Foundational textbook on customer engagement, brand positioning, digital marketing channels, analytics, and global market dynamics.',
      price: 690,
      rentalPrice: 125,
      stock: 8,
      availableStock: 6,
      condition: 'Good',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-02-08T10:00:00Z',
      featured: false
    },
    {
      id: 'book-12',
      title: 'Financial Accounting for Management',
      author: 'N. Ramachandran & Ram Kumar Kakani',
      isbn: '978-9353164997',
      categoryId: 'cat-commerce',
      categoryName: 'Commerce & Finance',
      subject: 'Accounting',
      semester: 'Semester 1',
      description: 'Structured course text covering corporate balance sheets, cash flow statements, IFRS compliance, financial ratio analysis, and corporate valuation.',
      price: 540,
      rentalPrice: 90,
      stock: 10,
      availableStock: 8,
      condition: 'Like New',
      rentEnabled: true,
      returnDurationDays: 30,
      sellerId: 'admin-1',
      sellerName: 'BookNest Campus Store',
      status: 'approved',
      images: ['https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80'],
      createdAt: '2026-02-12T15:30:00Z',
      featured: false
    }
  ],

  users: [
    {
      uid: 'admin-1',
      name: 'System Administrator',
      email: 'admin@booknest.edu',
      phone: '+91 9876543210',
      college: 'National Institute of Technology',
      course: 'Computer Science & Engineering',
      year: 'Faculty / Admin',
      role: 'admin',
      status: 'active',
      photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      createdAt: '2025-12-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z'
    },
    {
      uid: 'student-1',
      name: 'Alex Johnson',
      email: 'alex.student@college.edu',
      phone: '+91 9123456780',
      college: 'City Engineering College',
      course: 'B.Tech Information Technology',
      year: '3rd Year',
      role: 'student',
      status: 'active',
      photoURL: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=200&q=80',
      createdAt: '2026-01-05T00:00:00Z',
      updatedAt: '2026-01-05T00:00:00Z'
    }
  ],

  listings: [
    {
      id: 'list-101',
      sellerId: 'student-1',
      sellerName: 'Alex Johnson',
      sellerEmail: 'alex.student@college.edu',
      title: 'Digital Signal Processing (Principles & Algorithms)',
      author: 'John G. Proakis',
      isbn: '978-0131873742',
      categoryId: 'cat-eng',
      categoryName: 'Engineering',
      subject: 'Signal Processing',
      semester: 'Semester 5',
      condition: 'Good',
      description: 'Used for one semester. Highlights on chapter 3 and 4, all pages intact.',
      price: 420,
      rentalPrice: 75,
      quantity: 1,
      rentEnabled: true,
      images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80'],
      status: 'pending',
      rejectionReason: '',
      createdAt: '2026-02-18T10:00:00Z',
      updatedAt: '2026-02-18T10:00:00Z'
    }
  ],

  orders: [
    {
      id: 'ORD-98210',
      userId: 'student-1',
      userName: 'Alex Johnson',
      userEmail: 'alex.student@college.edu',
      userPhone: '+91 9123456780',
      deliveryMethod: 'Campus Pickup',
      pickupLocation: 'Main Library Counter 2',
      shippingAddress: 'Hostel Block B, Room 304, Campus Grounds',
      items: [
        {
          bookId: 'book-1',
          title: 'Data Structures and Algorithms Made Easy',
          author: 'Narasimha Karumanchi',
          price: 499,
          quantity: 1,
          type: 'buy',
          image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80'
        }
      ],
      subtotal: 499,
      deliveryFee: 0,
      total: 499,
      status: 'Ready',
      paymentMethod: 'Campus Pay (Simulated)',
      paymentStatus: 'Paid',
      createdAt: '2026-02-15T14:30:00Z',
      updatedAt: '2026-02-16T09:00:00Z'
    }
  ],

  rentals: [
    {
      id: 'RNT-44012',
      userId: 'student-1',
      userName: 'Alex Johnson',
      userEmail: 'alex.student@college.edu',
      bookId: 'book-3',
      bookTitle: 'Operating System Concepts (10th Edition)',
      bookAuthor: 'Abraham Silberschatz',
      bookImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80',
      issueDate: '2026-02-01T10:00:00Z',
      dueDate: '2026-03-03T10:00:00Z',
      returnDate: null,
      rentalPrice: 140,
      durationDays: 30,
      status: 'Active',
      createdAt: '2026-02-01T10:00:00Z',
      updatedAt: '2026-02-01T10:00:00Z'
    }
  ]
};

window.BookNestSeedData = BookNestSeedData;
